CC=avr-gcc
AS=$(CC)
LD=$(CC)

PROGNAME=atmega328p_open15button_8MHz
OBJDIR=objs-$(PROGNAME)
CPU=atmega328p
CFLAGS=-Wall -mmcu=$(CPU) -DF_CPU=8000000L -Os -DWITH_SNES -DWITH_15_BUTTONS -DWITH_EEPROM
LDFLAGS=-mmcu=$(CPU) -Wl,-Map=$(PROGNAME).map
HEXFILE=$(PROGNAME).hex
AVRDUDE=avrdude -p m328p -P usb -c avrispmkII

#  -  -  -  -  -  BODLEVEL2  BODLEVEL1  BODLEVEL0
#  0  0  0  0  0     1          1          1
#EFUSE=0x07 (but usually shows as 0xFF on AVRDUDE with AVRISP)
EFUSE=0xFF

# RSTDISBL  DWEN  SPIEN   WDTON  EESAVE  BOOTSZ1    BOOOTSZ2  BOOTRST
#    1        1      0      1      1         0          0        1
HFUSE=0xd9
#
# CKDIV8   CKOUT   SUT1  SUT0  CKSEL3  CKSEL2  CKSEL1  CKSEL0
#    1        1      1     0      0      0       1       0
#
# 8mhz internal RC oscillator (Ok for NES/SNES only mode)
LFUSE=0xE2

OBJS=$(addprefix $(OBJDIR)/, main.o wiimote.o clsc.o eeprom.o classic.o)

all: $(HEXFILE)

clean:
	rm -f $(PROGNAME).elf $(PROGNAME).hex $(PROGNAME).map $(OBJS)

$(OBJDIR)/%.o: %.S
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR)/%.o: %.c %.h
	$(CC) $(CFLAGS) -c $< -o $@

$(PROGNAME).elf: $(OBJS)
	$(LD) $(OBJS) $(LDFLAGS) -o $(PROGNAME).elf

$(PROGNAME).hex: $(PROGNAME).elf
	avr-objcopy -j .data -j .text -O ihex $(PROGNAME).elf $(PROGNAME).hex
	avr-size $(PROGNAME).elf

fuse:
	#$(AVRDUDE) -e -Uefuse:w:$(EFUSE):m -Uhfuse:w:$(HFUSE):m -Ulfuse:w:$(LFUSE):m -B 20.0 -v
	$(AVRDUDE) -e -Uefuse:w:$(EFUSE):m -Uhfuse:w:$(HFUSE):m -Ulfuse:w:$(LFUSE):m -B 5.0 -v

flash: $(HEXFILE)
	#$(AVRDUDE) -Uflash:w:$(HEXFILE) -B 1.0 -F
	$(AVRDUDE) -Uflash:w:$(HEXFILE) -B 5.0

chip_erase:
	$(AVRDUDE) -e -B 1.0 -F

reset:
	$(AVRDUDE) -B 1.0 -F
	
